### ISSUE TITLE
java.lang.NoSuchFieldError: future

### ISSUE THREAD

**Issue by Dbzman** [link-nv/logback-s3-rolling-policy#6]
Hey,
we wanted to use this library in a play 2.5 application but it crashes when it tries to upload the files:
```
Exception in thread "pool-64-thread-1" java.lang.NoSuchFieldError: future
	at ch.qos.logback.core.rolling.S3TimeBasedRollingPolicy.waitForAsynchronousJobToStop(S3TimeBasedRollingPolicy.java:158)
	at ch.qos.logback.core.rolling.S3TimeBasedRollingPolicy.access$000(S3TimeBasedRollingPolicy.java:37)
	at ch.qos.logback.core.rolling.S3TimeBasedRollingPolicy$UploadQueuer.run(S3TimeBasedRollingPolicy.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
By looking at the code it seems valid because "future" does not exist.

**Comment by Dbzman** [comment]
Someone seems to have fixed it already. :)
https://github.com/SiteFlo/logback-s3-rolling-policy
